### ISSUE TITLE
How should use other video

### ISSUE THREAD

**Issue by SamTop** [FollowTheDarkside/aframe-arjs-plane-video#1]
Hi, great work! I want to use this video and its10th frame as an nft, but the video does not appear. I think it is because of some wrong properties. Maybe add in readme info about how to use other assets?

**Comment by FollowTheDarkside** [comment]
Are you referring to the videos in the assets directory of this repository? Whether that is the case or your own video, please export the 10th frame as a still image and create a marker with the NFT Marker Creator.
https://carnaux.github.io/NFT-Marker-Creator/#/

For the basic flow for marker recognition, I recommend referring to the official AR.js documentation and sample code.
https://ar-js-org.github.io/AR.js-Docs/

As a reminder, please note that my images and videos are created using The NDL Image Bank and are subject to their own terms of use. I will also add the MIT license for the source code later.
